# Generated by Django 4.2.2 on 2023-06-28 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='watchlisted',
        ),
        migrations.AddField(
            model_name='product',
            name='watchlisted_by',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
