# Generated by Django 4.2.2 on 2023-06-29 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_product_watchlisted_product_watchlisted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatbid', to='auctions.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='watchlisted_by',
            field=models.ManyToManyField(default=1, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
